### PR TITLE
Replace deprecated references to FStringClassReference

### PR DESCRIPTION
**Pull request by douglaslassance**

### CODE REVIEW

**Comment by WiggleWizard** [comment]
Is this backwards compatible with UE4? I want to keep this project's backcompat ethos (to a certain degree).

**Comment by douglaslassance** [comment]
`FSoftClassPath` is there, but I'll give a try and let you know.

**Comment by douglaslassance** [comment]
My change compiles fine with `4.26.1`. That said the change you made with 56987d244f057614f2d073df8178dd48a0826f35 on line 32 of `Source/ImGui/Private/ImGuiDrawData.cpp` does not.

```
Building 4 actions with 16 processes...
  [1/4] Module.ImGui.cpp
  Plugins/ImGui/Source/ImGui/Private/ImGuiDrawData.cpp(32): error C2065: 'FVector2f': undeclared identifier
  Plugins/ImGui/Source/ImGui/Private/ImGuiDrawData.cpp(32): error C2146: syntax error: missing ';' before identifier 'Transform'
```

**Comment by WiggleWizard** [comment]
Will take a look at that, thanks for letting me know!
